name: Heroku Awake

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: fjogeleit/http-request-action@master
        with:
          url: 'https://prediction-weather-app.herokuapp.com/predict/'
          method: 'POST'